DROP TRIGGER IF EXISTS decision_budget_events_immutable ON decision_budget_events;
DROP TRIGGER IF EXISTS decision_records_immutable ON decision_records;
DROP TRIGGER IF EXISTS decision_verifications_immutable ON decision_verifications;
DROP TRIGGER IF EXISTS decision_observations_immutable ON decision_observations;
DROP TRIGGER IF EXISTS decision_graph_edges_immutable ON decision_graph_edges;
DROP TRIGGER IF EXISTS decision_graph_versions_immutable ON decision_graph_versions;
DROP TRIGGER IF EXISTS decision_graph_runs_update_guard ON decision_graph_runs;
DROP TRIGGER IF EXISTS decision_graph_nodes_update_guard ON decision_graph_nodes;
DROP TRIGGER IF EXISTS decision_graph_edges_cycle_guard ON decision_graph_edges;
DROP FUNCTION IF EXISTS decision_graph_immutable_row();
DROP FUNCTION IF EXISTS decision_graph_guard_run_update();
DROP FUNCTION IF EXISTS decision_graph_guard_node_update();
DROP FUNCTION IF EXISTS decision_graph_reject_edge_cycle();
DROP TABLE IF EXISTS decision_budget_events;
DROP TABLE IF EXISTS decision_records;
DROP TABLE IF EXISTS decision_verifications;
DROP TABLE IF EXISTS decision_observations;
DROP TABLE IF EXISTS decision_node_executions;
DROP TABLE IF EXISTS decision_graph_budgets;
DROP TABLE IF EXISTS decision_graph_edges;
DROP TABLE IF EXISTS decision_graph_nodes;
DROP TABLE IF EXISTS decision_graph_versions;
DROP TABLE IF EXISTS decision_graph_runs;
