package questionidentity

import (
	"encoding/json"
	"reflect"
	"testing"
)

func TestControllerBindingAllowsTypedNarrowingAndOwnsTask(t *testing.T) {
	payload := mustControllerRequest(t, ControllerRefinementRequest{
		SchemaVersion:           ControllerBindingSchemaV1,
		CanonicalContractSHA256: CanonicalContractSHA256,
		QuestionID:              "REFORMULATED-Q3-002",
		RefinementProfile:       PredicateResolveUnclassifiedSourceEntries,
	})

	outcome, err := BindControllerPayload(payload)
	if err != nil {
		t.Fatalf("BindControllerPayload() error = %v", err)
	}
	if !outcome.Decision.Accepted() || !outcome.ProviderCallAllowed || outcome.AuthorizedTask == nil {
		t.Fatalf("typed narrowing rejected: %#v", outcome)
	}
	if outcome.AuthorizedTask.QuestionID != "REFORMULATED-Q3-002" {
		t.Fatalf("authorized task lost question identity: %#v", outcome.AuthorizedTask)
	}
	if outcome.AuthorizedTask.AssignmentID != "Q3-002-RESOLVE-UNCLASSIFIED-SOURCE-ENTRIES" {
		t.Fatalf("task was not generated by the canonical profile: %#v", outcome.AuthorizedTask)
	}
}

func TestControllerBindingRejectsFreeFormHistoricalDrift(t *testing.T) {
	payload := []byte(`{"assignment_id":"REFORMULATED-Q3-001-EVIDENCE-003","question_id":"REFORMULATED-Q3-001","objective":"search exactly five custom mechanisms"}`)
	outcome, err := BindControllerPayload(payload)
	if err != nil {
		t.Fatalf("BindControllerPayload() error = %v", err)
	}
	if outcome.Decision.Accepted() || outcome.ProviderCallAllowed || outcome.AuthorizedTask != nil {
		t.Fatalf("free-form historical drift accepted: %#v", outcome)
	}
	assertRejectedWithFields(t, outcome.Decision, []ContractField{FieldPayload})
}

func TestControllerBindingRejectsUnknownProfile(t *testing.T) {
	payload := mustControllerRequest(t, ControllerRefinementRequest{
		SchemaVersion:           ControllerBindingSchemaV1,
		CanonicalContractSHA256: CanonicalContractSHA256,
		QuestionID:              "REFORMULATED-Q3-002",
		RefinementProfile:       NarrowingPredicateID("literal_phrase_exists"),
	})
	outcome, err := BindControllerPayload(payload)
	if err != nil {
		t.Fatalf("BindControllerPayload() error = %v", err)
	}
	if outcome.ProviderCallAllowed || outcome.AuthorizedTask != nil {
		t.Fatalf("unknown profile reached provider path: %#v", outcome)
	}
	assertRejectedWithFields(t, outcome.Decision, []ContractField{FieldNarrowingPredicates})
}

func TestControllerBindingReplayIsDeterministic(t *testing.T) {
	payload := mustControllerRequest(t, ControllerRefinementRequest{
		SchemaVersion:           ControllerBindingSchemaV1,
		CanonicalContractSHA256: CanonicalContractSHA256,
		QuestionID:              "REFORMULATED-Q3-002",
		RefinementProfile:       PredicateResolveUnclassifiedSourceEntries,
	})
	first, err := BindControllerPayload(payload)
	if err != nil {
		t.Fatalf("first BindControllerPayload() error = %v", err)
	}
	second, err := BindControllerPayload(payload)
	if err != nil {
		t.Fatalf("second BindControllerPayload() error = %v", err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("same input produced different outcomes:\nfirst=%#v\nsecond=%#v", first, second)
	}
}

func mustControllerRequest(t *testing.T, request ControllerRefinementRequest) []byte {
	t.Helper()
	payload, err := json.Marshal(request)
	if err != nil {
		t.Fatalf("json.Marshal() error = %v", err)
	}
	return payload
}
