package executive

import "encoding/json"

var (
	executivePlanOutputSchema    = json.RawMessage(`{"type":"object","additionalProperties":false,"required":["schema_version","objective","department_requests","global_constraints","success_criteria","owner_decisions_required"],"properties":{"schema_version":{"type":"string","const":"executive-plan/v1"},"objective":{"type":"string"},"department_requests":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["unit_id","objective","deliverable","priority","constraints"],"properties":{"unit_id":{"type":"string"},"objective":{"type":"string"},"deliverable":{"type":"string"},"priority":{"type":"integer"},"constraints":{"type":"array","items":{"type":"string"}}}}},"global_constraints":{"type":"array","items":{"type":"string"}},"success_criteria":{"type":"array","items":{"type":"string"}},"owner_decisions_required":{"type":"array","items":{"type":"string"}}}}`)
	departmentPlanOutputSchema   = json.RawMessage(`{"type":"object","additionalProperties":false,"required":["schema_version","department_id","tasks","review_criteria","unresolved"],"properties":{"schema_version":{"type":"string","const":"department-plan/v1"},"department_id":{"type":"string"},"tasks":{"type":"array","items":{"$ref":"#/$defs/task"}},"review_criteria":{"type":"array","items":{"type":"string"}},"unresolved":{"type":"array","items":{"type":"string"}}},"$defs":{"requirement":{"type":"object","additionalProperties":false,"required":["key","type","description","required"],"properties":{"key":{"type":"string"},"type":{"type":"string","enum":["artifact","check","approval","condition","result"]},"description":{"type":"string"},"required":{"type":"boolean"}}},"task":{"type":"object","additionalProperties":false,"required":["client_key","assigned_role_id","title","instructions","acceptance_criteria","dependencies","requirements","priority"],"properties":{"client_key":{"type":"string"},"assigned_role_id":{"type":"string"},"title":{"type":"string"},"instructions":{"type":"string"},"acceptance_criteria":{"type":"array","items":{"type":"string"}},"dependencies":{"type":"array","items":{"type":"string"}},"requirements":{"type":"array","items":{"$ref":"#/$defs/requirement"}},"priority":{"type":"integer"}}}}}`)
	workerResultOutputSchema     = json.RawMessage(`{"type":"object","additionalProperties":false,"required":["schema_version","summary","evidence_refs"],"properties":{"schema_version":{"type":"string","const":"worker-result/v1"},"summary":{"type":"string"},"evidence_refs":{"type":"array","items":{"type":"string"}}}}`)
	departmentReviewOutputSchema = json.RawMessage(`{"type":"object","additionalProperties":false,"required":["schema_version","verdict","findings","unsatisfied_criteria","evidence_refs","proposed_followup_tasks"],"properties":{"schema_version":{"type":"string","const":"department-review/v1"},"verdict":{"type":"string","enum":["accept","needs_replan","blocked","fail"]},"findings":{"type":"array","items":{"type":"string"}},"unsatisfied_criteria":{"type":"array","items":{"type":"string"}},"evidence_refs":{"type":"array","items":{"type":"string"}},"proposed_followup_tasks":{"type":"array","items":{"type":"object"}}}}`)
	executiveClosureOutputSchema = json.RawMessage(`{"type":"object","additionalProperties":false,"required":["schema_version","status","answer_to_owner","completed_items","blocked_items","unresolved_decisions","evidence_refs"],"properties":{"schema_version":{"type":"string","const":"executive-closure/v1"},"status":{"type":"string","enum":["completed","partial","blocked","failed"]},"answer_to_owner":{"type":"string"},"completed_items":{"type":"array","items":{"type":"string"}},"blocked_items":{"type":"array","items":{"type":"string"}},"unresolved_decisions":{"type":"array","items":{"type":"string"}},"evidence_refs":{"type":"array","items":{"type":"string"}}}}`)
)
