import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}), headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage({viewport:{width:1536,height:1024}});
  const errors = [], requests = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => requests.push(r.url()));
  await page.goto('http://127.0.0.1:4184');
  await page.locator('.floor-art').waitFor();
  assert.equal(await page.locator('.room-label').count(), 6);
  assert.equal(await page.locator('.room-status').count(), 6);
  assert.deepEqual(await page.locator('.sidebar-tabs button').allTextContents(), ['Chat', 'Estado CEO', 'Tarea', 'Evidencia', 'Actividad']);
  assert.equal(await page.locator('.sidebar-tabs button[aria-selected="true"]').innerText(), 'Estado CEO');
  await page.locator('[data-tab="chat"]').click();
  assert.equal(await page.locator('#ceo-chat-input').isVisible(), true);
  await page.locator('[data-tab="status"]').click();
  assert.equal(await page.locator('.assignment').count(), 1);
  for (let i = 0; i < 3; i++) {
    await page.locator('#mission-select').selectOption(String(i));
    assert.equal(await page.locator('.agent[data-person="ceo"]').count(), 1);
    assert.equal(await page.locator('.agent[data-person="research"]').count(), 1);
    assert.equal(await page.locator('.agent').count(), i === 1 ? 4 : 5);
  }
  await page.locator('#mission-select').selectOption('0');
  await page.locator('.agent[data-person="fe"]').click();
  assert.match(await page.locator('.task').innerText(), /explorador/);
  assert.match(await page.locator('.agent-work-card').innerText(), /Construyendo la vista/);
  assert.equal(await page.locator('.agent-bubble').count(), 5);
  assert.match(await page.locator('.agent[data-person="fe"]').getAttribute('aria-label'), /Construyendo/);
  await page.locator('[data-tab="evidence"]').click();
  assert.match(await page.locator('#detail-panel').innerText(), /Aún no hay evidencia/);
  await page.locator('[data-action="next"]').click();
  await page.locator('[data-action="evidence"]').click();
  assert.match(await page.locator('#evidence-body').innerText(), /no procede de un agente ni del VPS/);
  await page.locator('[data-tab="activity"]').click();
  assert.match(await page.locator('#detail-panel').innerText(), /Actividad de Frontend/);
  assert.match(await page.locator('#detail-panel').innerText(), /Revisando recorridos/);
  await page.locator('[data-tab="activity"]').press('Home');
  assert.equal(await page.locator('#tab-chat').getAttribute('aria-selected'), 'true');
  await page.locator('[data-action="next"]').click();
  assert.equal(await page.locator('[data-action="play"]').isDisabled(), true);
  assert.equal(await page.locator('.mission-result').count(), 1);
  assert.match(await page.locator('.mission-result').innerText(), /Memoria compartida lista para revisión/);
  assert.doesNotMatch(await page.locator('.floor-scene').innerText(), /0 perfiles activos/);
  await page.locator('[data-tab="result"]').click();
  assert.match(await page.locator('#detail-panel').innerText(), /Contrato de memoria/);
  await page.locator('[data-action="reset"]').click();
  await page.locator('[data-action="play"]').click();
  await page.locator('.agent[data-person="fe"]').focus();
  await page.waitForTimeout(5200);
  assert.equal(await page.locator('.agent[data-person="fe"]').evaluate(el => el === document.activeElement), true);
  assert.match(await page.locator('.phase-label').innerText(), /Construir/);
  await page.locator('[data-action="play"]').click();
  await page.locator('[data-action="in"]').click();
  assert.equal(await page.locator('output').innerText(), '125%');
  await page.locator('[data-action="fit"]').click();
  assert.equal(await page.locator('output').innerText(), '100%');
  await page.locator('.room-label[data-room="business"]').click();
  assert.match(await page.locator('.inspector').innerText(), /Sin asignaciones/);
  await page.locator('[data-view="missions"]').click();
  assert.equal(await page.locator('.mission-card').count(), 3);
  await page.locator('[data-mission="0"]').click();
  await page.locator('[data-tab="chat"]').click();
  await page.locator('#ceo-chat-input').fill('Dame un resumen del estado');
  await page.locator('#ceo-chat-form').evaluate(form => form.requestSubmit());
  await page.locator('.ceo-chat-message.ceo').last().waitFor();
  assert.match(await page.locator('.ceo-chat-messages').innerText(), /CEO simulado/);
  await page.locator('#ceo-chat-input').fill('/mision Preparar demo local');
  await page.locator('#ceo-chat-form').evaluate(form => form.requestSubmit());
  await page.locator('#mission-composer-form').waitFor();
  assert.equal(await page.locator('#mission-objective').inputValue(), 'Preparar demo local');
  await page.locator('[data-chat-cancel]').click();
  assert.equal(await page.locator('#mission-composer-form').count(), 0);
  await mkdir('.impeccable/review', {recursive:true});
  for (const [name,width,height] of [['approved-size',1536,1024],['desktop',1440,1050],['narrow',1024,768],['mobile',390,844]]) {
    await page.setViewportSize({width,height});
    await page.evaluate(() => { scrollTo(0,0); document.querySelector('.floor-viewport').scrollTo(0,0); });
    await page.screenshot({path:`.impeccable/review/${name}.png`,fullPage:true});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, name);
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('.agent[data-person="research"]').click();
  assert.equal(await page.locator('#person-details').evaluate(el => el === document.activeElement), true);
  await page.locator('[data-action="return"]').click();
  assert.equal(await page.locator('.agent[data-person="research"]').evaluate(el => el === document.activeElement), true);
  assert.deepEqual(requests.filter(url => !url.startsWith('http://127.0.0.1:4184/')), []);
  assert.deepEqual(requests.filter(url => url.includes('/api/')), []);
  assert.deepEqual(errors, []);
  console.log('PASS: occupancy, permanent roles, room and agent selection, evidence, activity, keyboard tabs, playback/focus, reset, zoom, mission navigation, responsive overflow, mobile return, no external or API requests.');
} finally { await browser.close(); }
